# Generated by Django 4.2.2 on 2023-06-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundFlow_models', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='energia',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medallas',
            field=models.ManyToManyField(blank=True, to='soundFlow_models.medalla'),
        ),
        migrations.AddField(
            model_name='user',
            name='trofeos',
            field=models.ManyToManyField(blank=True, to='soundFlow_models.trofeo'),
        ),
    ]
