# Generated by Django 4.2.2 on 2023-06-29 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('min_energia', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Medalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='medallas/')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('nivel', models.IntegerField(default=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='trofeos/')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trofeos', to='soundFlow_models.desafio')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTrofeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trofeo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_trofeos', to='soundFlow_models.trofeo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_trofeos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioMedallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medalla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundFlow_models.medalla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_nivel', to='soundFlow_models.desafio')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_nivel', to='soundFlow_models.nivel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_nivel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.TextField()),
                ('resultado', models.TextField()),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='soundFlow_models.desafio')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='prueba/imagen/')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='soundFlow_models.prueba')),
            ],
        ),
        migrations.AddField(
            model_name='desafio',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soundFlow_models.nivel'),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='prueba/audios/')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='soundFlow_models.prueba')),
            ],
        ),
    ]
