# Generated by Django 4.2.2 on 2023-06-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundFlow_models', '0002_pruebasresueltasuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernivel',
            name='is_resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
