from .nivel import Nivel
from .desafio import Desafio
from .prueba import Prueba
from .trofeo import Trofeo
from .medalla import Medalla
from .imagen import Imagen
from .audio import Audio
from .user_nivel import UserNivel
from .usuario_trofeos import UsuarioTrofeos
from .usuario_medallas import UsuarioMedallas
from .pruebas_resueltas_user import PruebasResueltasUser